name: Run get kintone records

on:
  workflow_dispatch: 
  pull_request:

jobs:
  getdata:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: install kintone-api-client
        run: npm install @kintone/rest-api-client
      - name: install kintone-api-client
        run: export KINTONE_API_TOKEN=env.JNKYKN_KINTONE_API_TOKEN_APPID2
      - name: test job(get kintone records)
        run: node jobs/getKintoneRecords.js
      