name: Run get kintone records

on:
  workflow_dispatch: 
  pull_request:

jobs:
  getdata:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: test job(get kintone records)
        run: node jobs/getKintoneRecords.js
      