name: Run testjob

on: pull_request

jobs:
  textlint:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: test job(local repo)
        run: node src/testjob.js
      